INSERT INTO `items` (`name`, `label`, `weight`, `rare`, `can_remove`) VALUES
	('idrp_vape_morph',	'idrp_vape_morph', 1, 0, 1),
	("idrp_vape_gblue", 'idrp_vape_gblue', 1, 0, 1),
	("idrp_vape_ggreen", 'idrp_vape_ggreen', 1, 0, 1),
	("idrp_vape_gcyan", 'idrp_vape_gcyan', 1, 0, 1),
	("idrp_vape_gpurple", 'idrp_vape_gpurple', 1, 0, 1),
	("idrp_vape_gred", 'idrp_vape_gred', 1, 0, 1),
	("idrp_vape_gyellow", 'idrp_vape_gyellow', 1, 0, 1),
	("idrp_vape_lgblue", 'idrp_vape_lgblue', 1, 0, 1),
	("idrp_vape_lggreen", 'idrp_vape_lggreen', 1, 0, 1),
	("idrp_vape_lgcyan", 'idrp_vape_lgcyan', 1, 0, 1),
	("idrp_vape_lgpurple", 'idrp_vape_lgpurple', 1, 0, 1),
	("idrp_vape_lgred", 'idrp_vape_lgred', 1, 0, 1),
	("idrp_vape_lgyellow", 'idrp_vape_lgyellow', 1, 0, 1),
	("idrp_vape_mmorph", 'idrp_vape_mmorph', 1, 0, 1),
	("idrp_vape_mgreen", 'idrp_vape_mgreen', 1, 0, 1),
	("idrp_vape_mpurple", 'idrp_vape_mpurple', 1, 0, 1),
	("idrp_vape_mred", 'idrp_vape_mred', 1, 0, 1),
	("idrp_vape_myellow", 'idrp_vape_myellow', 1, 0, 1),
	("idrp_vape_mblue", 'idrp_vape_mblue', 1, 0, 1),
	("idrp_vape_mcyan", 'idrp_vape_mcyan', 1, 0, 1)
;
